### ISSUE TITLE
gulp deploy failed

### ISSUE THREAD

**Issue by onlyice** [zhangmhao/Life-Time-Tracker#5]
After installing all the dependency, I run `gulp deploy` but it is not working:

```
> gulp deploy
[07:56:25] Using gulpfile ~/workspace/Life-Time-Tracker/gulpfile.js
(node:13334) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[07:56:25] Starting 'deploy'...
Building APP bundle
Building VENDORS bundle
[07:56:25] Finished 'deploy' after 27 ms
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Deps.lookupPackage (/home/onlyice/workspace/Life-Time-Tracker/node_modules/module-deps/index.js:452:29)
    at Deps._transform (/home/onlyice/workspace/Life-Time-Tracker/node_modules/module-deps/index.js:93:10)
    at Deps.Transform._read (/home/onlyice/workspace/Life-Time-Tracker/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Deps.Transform._write (/home/onlyice/workspace/Life-Time-Tracker/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at Labeled.Pipeline._write (/home/onlyice/workspace/Life-Time-Tracker/node_modules/stream-splicer/index.js:73:22)
    at doWrite (/home/onlyice/workspace/Life-Time-Tracker/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/onlyice/workspace/Life-Time-Tracker/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Labeled.Writable.write (/home/onlyice/workspace/Life-Time-Tracker/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Labeled.ondata (/home/onlyice/workspace/Life-Time-Tracker/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at emitOne (events.js:96:13)
    at Labeled.emit (events.js:191:7)
    at readableAddChunk (/home/onlyice/workspace/Life-Time-Tracker/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Labeled.Readable.push (/home/onlyice/workspace/Life-Time-Tracker/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Labeled.Pipeline._read (/home/onlyice/workspace/Life-Time-Tracker/node_modules/stream-splicer/index.js:57:31)
```

- OS: Arch Linux
- Gulp 3.9.1

**Comment by onlyice** [comment]
I've seen the declaration on README that this project supports only MacOS. But afaik Linux is not much different to MacOS. Is this problem caused by just the node packages but not the operation system?

**Comment by cosisoft** [comment]
@onlyice do you solve this problem
