### ISSUE TITLE
windows7 x64 gulp deploy failed

### ISSUE THREAD

**Issue by cosisoft** [zhangmhao/Life-Time-Tracker#8]
(node:7404) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpd
ir() instead.
[11:28:14] Starting 'deploy'...
Building APP bundle
Building VENDORS bundle
[11:28:14] Finished 'deploy' after 75 ms
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Re
ceived type undefined
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:651:5)
    at Deps.lookupPackage (C:\Users\zhanglq\Downloads\Life-Time-Tracker-master\n
ode_modules\module-deps\index.js:452:29)
    at Deps._transform (C:\Users\zhanglq\Downloads\Life-Time-Tracker-master\node
_modules\module-deps\index.js:93:10)
    at Deps.Transform._read (C:\Users\zhanglq\Downloads\Life-Time-Tracker-master
\node_modules\module-deps\node_modules\readable-stream\lib\_stream_transform.js:
184:10)
    at Deps.Transform._write (C:\Users\zhanglq\Downloads\Life-Time-Tracker-maste
r\node_modules\module-deps\node_modules\readable-stream\lib\_stream_transform.js
:172:12)
    at Labeled.Pipeline._write (C:\Users\zhanglq\Downloads\Life-Time-Tracker-mas
ter\node_modules\stream-splicer\index.js:73:22)
    at doWrite (C:\Users\zhanglq\Downloads\Life-Time-Tracker-master\node_modules
\stream-splicer\node_modules\readable-stream\lib\_stream_writable.js:279:12)
    at writeOrBuffer (C:\Users\zhanglq\Downloads\Life-Time-Tracker-master\node_m
odules\stream-splicer\node_modules\readable-stream\lib\_stream_writable.js:266:5
)
    at Labeled.Writable.write (C:\Users\zhanglq\Downloads\Life-Time-Tracker-mast
er\node_modules\stream-splicer\node_modules\readable-stream\lib\_stream_writable
.js:211:11)
    at Labeled.ondata (C:\Users\zhanglq\Downloads\Life-Time-Tracker-master\node_
modules\stream-splicer\node_modules\readable-stream\lib\_stream_readable.js:572:
20)
    at Labeled.emit (events.js:189:13)
    at Labeled.EventEmitter.emit (domain.js:441:20)
    at readableAddChunk (C:\Users\zhanglq\Downloads\Life-Time-Tracker-master\nod
e_modules\stream-splicer\node_modules\readable-stream\lib\_stream_readable.js:19
5:16)
    at Labeled.Readable.push (C:\Users\zhanglq\Downloads\Life-Time-Tracker-maste
r\node_modules\stream-splicer\node_modules\readable-stream\lib\_stream_readable.
js:162:10)
    at Labeled.Pipeline._read (C:\Users\zhanglq\Downloads\Life-Time-Tracker-mast
er\node_modules\stream-splicer\index.js:57:31)

**Comment by cosisoft** [comment]
Is it only support MacOS, not support Windows system?
